In [58]:
import pandas as pd

In [59]:
# 读取C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于COX_sur的特征数据集.csv
data = pd.read_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于COX_sur的特征数据集.csv')
# 读取C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于统计的完整数据集.csv
data2 = pd.read_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于统计的完整数据集.csv')
# 读取C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv
data3 = pd.read_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv')

In [60]:
# 按照Subject_id合并data和data2，，只保留data2中的Admittime，Deathtime和Dod列
data = pd.merge(data, data2[['Subject_id', 'Admittime', 'Deathtime', 'Dod']], on='Subject_id')

# 按照

In [61]:
# 对于data3中D180D列不为0的行，使用Deathtime列的时间减去Admittime列的时间，以天做单位，精确到小数点后1位，替换T.O.D_180d列的值，如果Deathtime列的值为NaN，则使用Dod列的值.Apply this operation only to rows where 'D180D' is not 0。T.O.D_180d列中空值填充为180，大于180的值更改为180
# Convert to datetime if not already
data3['Admittime'] = pd.to_datetime(data3['Admittime'])
data3['Deathtime'] = pd.to_datetime(data3['Deathtime'])
data3['Dod'] = pd.to_datetime(data3['Dod'])

# Calculate the difference in days and round to 1 decimal place
data3.loc[data3['D180D'] != 0, 'T.O.D_180d'] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
data3['T.O.D_180d'] = data3['T.O.D_180d'].round(4)

# Replace 'T.O.D_180d' with 'Dod' where 'Deathtime' is NaN
data3.loc[data3['Deathtime'].isna() & (data3['D180D'] != 0), 'T.O.D_180d'] = (data3['Dod'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
data3['T.O.D_180d'] = data3['T.O.D_180d'].round(1)


# Fill NaN values with 180 and replace values greater than 180 with 180
data3['T.O.D_180d'].fillna(180, inplace=True)
data3.loc[data3['T.O.D_180d'] > 180, 'T.O.D_180d'] = 180

C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\3227604020.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[4.31666667e+00            nan            nan            nan
            nan            nan 1.79861111e-01            nan
            nan 2.85291667e+01 1.41909722e+01 9.79166667e-01
 3.29236111e+00 6.37500000e-01            nan            nan
 2.10694444e+00 6.63888889e+00            nan            nan
            nan 2.74513889e+01 1.72236111e+01 1.90243056e+01
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 1.70138889e-01 1.09027778e-01 3.15763889e+00 2.70833333e+01
 3.68750000e+00 9.60208333e+00 1.24180556e+01            nan
            nan            nan            nan 6.18055556e-02
 1.19027778e+00 1.01979167e+01 3.19444444e-01 5.85555556e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.39722222e+00 1.48409722e+01 5.77708333e+00
            nan            nan            nan            nan
            nan 2.18430556e+01 5.14791667e+00 3.46597222e+00
 6.02083333e+00            nan            nan            nan
            nan 1.08354167e+01 5.15402778e+01            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 4.68055556e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 1.41597222e+00
            nan            nan 3.92083333e+00            nan
            nan            nan            nan            nan
            nan            nan 1.53958333e+01 1.37250000e+01
            nan            nan            nan 1.35722222e+01
            nan            nan            nan 2.52430556e+00
 1.10187500e+01            nan 4.09722222e-02 1.97777778e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 8.15972222e-01 1.35902778e+00            nan
            nan            nan 4.35416667e-01            nan
            nan            nan            nan            nan
 3.06527778e+00 9.00833333e+00            nan            nan
 2.60486111e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan 2.96319444e+00            nan
            nan            nan            nan 1.41027778e+01
 1.01444444e+01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 4.25000000e-01 5.67083333e+00 6.36805556e-01
 5.42361111e-01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 9.76597222e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.32500000e+00            nan            nan
            nan 1.00743056e+01 1.78972222e+01 3.32361111e+00
 4.08333333e-01            nan            nan            nan
            nan            nan            nan 2.17819444e+01
 1.21805556e+00 5.29097222e+00            nan            nan
            nan            nan            nan            nan
            nan            nan 2.71805556e+00            nan]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data3.loc[data3['D180D'] != 0, 'T.O.D_180d'] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\3227604020.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3['T.O.D_180d'].fillna(180, inplace=True)

In [62]:
# Convert to datetime if not already
data3['Admittime'] = pd.to_datetime(data3['Admittime'])
data3['Deathtime'] = pd.to_datetime(data3['Deathtime'])
data3['Dod'] = pd.to_datetime(data3['Dod'])

# List of target columns and their corresponding limits
target_cols = [('T.O.D_90d', 90), ('T.O.D_60d', 60), ('T.O.D_31d', 31)]

for col, limit in target_cols:
    # Calculate the difference in days and round to 1 decimal place
    data3.loc[data3['D180D'] != 0, col] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
    data3[col] = data3[col].round(1)

    # Replace 'col' with 'Dod' where 'Deathtime' is NaN
    data3.loc[data3['Deathtime'].isna() & (data3['D180D'] != 0), col] = (data3['Dod'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
    data3[col] = data3[col].round(1)

    # Fill NaN values with limit and replace values greater than limit with limit
    data3[col].fillna(limit, inplace=True)
    data3.loc[data3[col] > limit, col] = limit

C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[4.31666667e+00            nan            nan            nan
            nan            nan 1.79861111e-01            nan
            nan 2.85291667e+01 1.41909722e+01 9.79166667e-01
 3.29236111e+00 6.37500000e-01            nan            nan
 2.10694444e+00 6.63888889e+00            nan            nan
            nan 2.74513889e+01 1.72236111e+01 1.90243056e+01
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 1.70138889e-01 1.09027778e-01 3.15763889e+00 2.70833333e+01
 3.68750000e+00 9.60208333e+00 1.24180556e+01            nan
            nan            nan            nan 6.18055556e-02
 1.19027778e+00 1.01979167e+01 3.19444444e-01 5.85555556e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.39722222e+00 1.48409722e+01 5.77708333e+00
            nan            nan            nan            nan
            nan 2.18430556e+01 5.14791667e+00 3.46597222e+00
 6.02083333e+00            nan            nan            nan
            nan 1.08354167e+01 5.15402778e+01            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 4.68055556e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 1.41597222e+00
            nan            nan 3.92083333e+00            nan
            nan            nan            nan            nan
            nan            nan 1.53958333e+01 1.37250000e+01
            nan            nan            nan 1.35722222e+01
            nan            nan            nan 2.52430556e+00
 1.10187500e+01            nan 4.09722222e-02 1.97777778e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 8.15972222e-01 1.35902778e+00            nan
            nan            nan 4.35416667e-01            nan
            nan            nan            nan            nan
 3.06527778e+00 9.00833333e+00            nan            nan
 2.60486111e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan 2.96319444e+00            nan
            nan            nan            nan 1.41027778e+01
 1.01444444e+01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 4.25000000e-01 5.67083333e+00 6.36805556e-01
 5.42361111e-01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 9.76597222e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.32500000e+00            nan            nan
            nan 1.00743056e+01 1.78972222e+01 3.32361111e+00
 4.08333333e-01            nan            nan            nan
            nan            nan            nan 2.17819444e+01
 1.21805556e+00 5.29097222e+00            nan            nan
            nan            nan            nan            nan
            nan            nan 2.71805556e+00            nan]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data3.loc[data3['D180D'] != 0, col] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3[col].fillna(limit, inplace=True)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[4.31666667e+00            nan            nan            nan
            nan            nan 1.79861111e-01            nan
            nan 2.85291667e+01 1.41909722e+01 9.79166667e-01
 3.29236111e+00 6.37500000e-01            nan            nan
 2.10694444e+00 6.63888889e+00            nan            nan
            nan 2.74513889e+01 1.72236111e+01 1.90243056e+01
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 1.70138889e-01 1.09027778e-01 3.15763889e+00 2.70833333e+01
 3.68750000e+00 9.60208333e+00 1.24180556e+01            nan
            nan            nan            nan 6.18055556e-02
 1.19027778e+00 1.01979167e+01 3.19444444e-01 5.85555556e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.39722222e+00 1.48409722e+01 5.77708333e+00
            nan            nan            nan            nan
            nan 2.18430556e+01 5.14791667e+00 3.46597222e+00
 6.02083333e+00            nan            nan            nan
            nan 1.08354167e+01 5.15402778e+01            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 4.68055556e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 1.41597222e+00
            nan            nan 3.92083333e+00            nan
            nan            nan            nan            nan
            nan            nan 1.53958333e+01 1.37250000e+01
            nan            nan            nan 1.35722222e+01
            nan            nan            nan 2.52430556e+00
 1.10187500e+01            nan 4.09722222e-02 1.97777778e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 8.15972222e-01 1.35902778e+00            nan
            nan            nan 4.35416667e-01            nan
            nan            nan            nan            nan
 3.06527778e+00 9.00833333e+00            nan            nan
 2.60486111e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan 2.96319444e+00            nan
            nan            nan            nan 1.41027778e+01
 1.01444444e+01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 4.25000000e-01 5.67083333e+00 6.36805556e-01
 5.42361111e-01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 9.76597222e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.32500000e+00            nan            nan
            nan 1.00743056e+01 1.78972222e+01 3.32361111e+00
 4.08333333e-01            nan            nan            nan
            nan            nan            nan 2.17819444e+01
 1.21805556e+00 5.29097222e+00            nan            nan
            nan            nan            nan            nan
            nan            nan 2.71805556e+00            nan]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data3.loc[data3['D180D'] != 0, col] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3[col].fillna(limit, inplace=True)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[4.31666667e+00            nan            nan            nan
            nan            nan 1.79861111e-01            nan
            nan 2.85291667e+01 1.41909722e+01 9.79166667e-01
 3.29236111e+00 6.37500000e-01            nan            nan
 2.10694444e+00 6.63888889e+00            nan            nan
            nan 2.74513889e+01 1.72236111e+01 1.90243056e+01
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 1.70138889e-01 1.09027778e-01 3.15763889e+00 2.70833333e+01
 3.68750000e+00 9.60208333e+00 1.24180556e+01            nan
            nan            nan            nan 6.18055556e-02
 1.19027778e+00 1.01979167e+01 3.19444444e-01 5.85555556e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.39722222e+00 1.48409722e+01 5.77708333e+00
            nan            nan            nan            nan
            nan 2.18430556e+01 5.14791667e+00 3.46597222e+00
 6.02083333e+00            nan            nan            nan
            nan 1.08354167e+01 5.15402778e+01            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
 4.68055556e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 1.41597222e+00
            nan            nan 3.92083333e+00            nan
            nan            nan            nan            nan
            nan            nan 1.53958333e+01 1.37250000e+01
            nan            nan            nan 1.35722222e+01
            nan            nan            nan 2.52430556e+00
 1.10187500e+01            nan 4.09722222e-02 1.97777778e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 8.15972222e-01 1.35902778e+00            nan
            nan            nan 4.35416667e-01            nan
            nan            nan            nan            nan
 3.06527778e+00 9.00833333e+00            nan            nan
 2.60486111e+00            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan 2.96319444e+00            nan
            nan            nan            nan 1.41027778e+01
 1.01444444e+01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 4.25000000e-01 5.67083333e+00 6.36805556e-01
 5.42361111e-01            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan            nan            nan 9.76597222e+00
            nan            nan            nan            nan
            nan            nan            nan            nan
            nan 5.32500000e+00            nan            nan
            nan 1.00743056e+01 1.78972222e+01 3.32361111e+00
 4.08333333e-01            nan            nan            nan
            nan            nan            nan 2.17819444e+01
 1.21805556e+00 5.29097222e+00            nan            nan
            nan            nan            nan            nan
            nan            nan 2.71805556e+00            nan]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data3.loc[data3['D180D'] != 0, col] = (data3['Deathtime'] - data3['Admittime']).dt.total_seconds() / (24 * 60 * 60)
C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2221726740.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3[col].fillna(limit, inplace=True)

In [64]:
# data3保存到C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv
data3.to_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv', index=False)

In [40]:
# 对于D180D列不为0的行，使用Deathtime列的时间减去Admittime列的时间，以天做单位，精确到小数点后1位，替换T_O_D_180d列的值，如果Deathtime列的值为NaN，则使用Dod列的值.Apply this operation only to rows where 'D180D' is not 0。T_O_D_180d列中空值填充为180，大于180的值更改为180
# Convert to datetime if not already
data['Admittime'] = pd.to_datetime(data['Admittime'])
data['Deathtime'] = pd.to_datetime(data['Deathtime'])
data['Dod'] = pd.to_datetime(data['Dod'])

# Calculate the difference in days and round to 1 decimal place
data['T_O_D_180d'] = (data['Deathtime'] - data['Admittime']).dt.total_seconds() / (24 * 60 * 60)
data['T_O_D_180d'] = data['T_O_D_180d'].round(4)

# Replace 'T_O_D_180d' with 'Dod' where 'Deathtime' is NaN
data.loc[data['Deathtime'].isna(), 'T_O_D_180d'] = (data['Dod'] - data['Admittime']).dt.total_seconds() / (24 * 60 * 60)
data['T_O_D_180d'] = data['T_O_D_180d'].round(1)

# Apply this operation only to rows where 'D180D' is not 0
data.loc[data['D180D'] != 0, 'T_O_D_180d'] = data['T_O_D_180d']

# T_O_D_180d列中空值填充为180，大于180的值更改为180
data['T_O_D_180d'].fillna(180, inplace=True)
data.loc[data['T_O_D_180d'] > 180, 'T_O_D_180d'] = 180

C:\Users\ZhouNan\AppData\Local\Temp\ipykernel_16160\2652455725.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['T_O_D_180d'].fillna(180, inplace=True)

In [41]:
# 删除data中Admittime，Deathtime和Dod列
data.drop(columns=['Admittime', 'Deathtime', 'Dod'], inplace=True)
# 保存data到C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于COX_sur的特征数据集.csv
data.to_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于COX_sur的特征数据集.csv', index=False)

In [19]:
import pandas as pd

In [20]:
# 读取C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv
data3 = pd.read_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv')
# 读取C:\MyProject\MIMIC-IPE\data\anti_combine.csv
data4 = pd.read_csv(r'C:\MyProject\MIMIC-IPE\data\anti_combine.csv')

In [21]:
# 将data4中列名首字母不是大写的列名改为首字母大写
data4.columns = [i.capitalize() for i in data4.columns]
# 去除data4中Prostate_cancer，Stomach_cancer，Colorectal_cancer，Breast_cancer几列的列名中的“_”
# Define a dictionary with the old column names as keys and new column names as values
rename_dict = {
    'Prostate_cancer': 'Prostate cancer',
    'Stomach_cancer': 'Stomach cancer',
    'Colorectal_cancer': 'Colorectal cancer',
    'Breast_cancer': 'Breast cancer'
}

# Use the rename function to change the column names
data4.rename(columns=rename_dict, inplace=True)

# Use the rename function to change the column names
data4.rename(columns=rename_dict, inplace=True)

In [22]:
# 按照Subject_id合并data3和data4，只保留data4中的Prostate_cancer，Stomach_cancer，Colorectal_cancer，Breast_cancer列
data3 = pd.merge(data3, data4[['Subject_id', 'Prostate cancer', 'Stomach cancer', 'Colorectal cancer', 'Breast cancer']], on='Subject_id')
# 去除

In [23]:
# 保存data3到C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv
data3.to_csv(r'C:\MyProject\MIMIC-IPE\加了中介变量的数据集\用于特征选择的数据集.csv', index=False)